# Generated by Django 6.0.2 on 2026-02-21 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("city", models.CharField(db_index=True, max_length=100)),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("calm", "Calm"),
                            ("adventurous", "Adventurous"),
                            ("curious", "Curious"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "budget_min",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("budget_max", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(help_text="Duration in minutes"),
                ),
                (
                    "avg_rating",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=3
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="routes/")),
                ("is_cover", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="RoutePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "duration_at_stop",
                    models.PositiveIntegerField(
                        default=0, help_text="Time to spend here in minutes"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="points/"),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True)),
                ("date_saved", models.DateTimeField(auto_now_add=True)),
                ("date_started", models.DateTimeField(blank=True, null=True)),
                ("date_completed", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date_saved"],
            },
        ),
    ]
