# Generated by Django 6.0.2 on 2026-02-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("parks", "Parks"),
                    ("museums", "Museums"),
                    ("cafes", "Cafes"),
                    ("mixed", "Mixed"),
                ],
                default="mixed",
                max_length=20,
            ),
        ),
    ]
